version: '2'
services:
  sonarr:
    image: linuxserver/sonarr
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr/config:/config
      - ./transmission/completed:/downloads
    restart: always
    ports:
      - 8989:8989
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  radarr:
    image: linuxserver/radarr
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./radarr/config:/config
      - ./transmission/completed:/downloads
    restart: always
    ports:
      - 7878:7878
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  jackett:
    image: linuxserver/jackett
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./jackett/config:/config
      - ./transmission/completed:/downloads
    ports:
      - 9117:9117
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    restart: always
  transmission:
    image: linuxserver/transmission
    volumes:
      - ./transmission/config.ovpn:/etc/openvpn/custom/default.ovpn
      - ./transmission:/data
      - /etc/localtime:/etc/localtime:ro
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9091:9091 
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
 