version: '2'
services:
  sonarr:
    image: linuxserver/sonarr
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr/config:/config
      - ./transmission/completed:/downloads
    restart: always
    ports:
      - 8989:8989
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Bucharest
  radarr:
    image: linuxserver/radarr
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./radarr/config:/config
      - ./transmission/completed:/downloads
    restart: always
    ports:
      - 7878:7878
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Bucharest
  jackett:
    image: linuxserver/jackett
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./jackett/config:/config
      - ./transmission/completed:/downloads
    ports:
      - 9117:9117
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Bucharest
    restart: always
  transmission:
    image: haugene/transmission-openvpn
    volumes:
      - ./transmission/config.ovpn:/etc/openvpn/custom/default.ovpn
      - ./transmission:/data
      - /etc/localtime:/etc/localtime:ro
      - /dev/net/tun:/dev/net/tun
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Bucharest
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=pass
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --dev tun
    ports:
      - 9091:9091 
      - 51413:51413
      - 51413:51413/udp
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

